FROM w251/tensorrt:dev-tx2-4.3_b132

RUN apt update
RUN apt install -y python3-pip wget
RUN pip3 install -U pip
RUN apt-get -y install cmake build-essential pkg-config libgoogle-perftools-dev

WORKDIR /tmp
RUN wget https://nvidia.box.com/shared/static/phqe92v26cbhqjohwtvxorrwnmrnfx1o.whl -O torch-1.3.0-cp36-cp36m-linux_aarch64.whl
ENV DEBIAN_FRONTEND=noninteractive
RUN pip3 install numpy torch-1.3.0-cp36-cp36m-linux_aarch64.whl

RUN pip3 install jupyter

RUN apt install -y \
    libsm6 \
    libxext6 \
    libxrender-dev \
    libgtk2.0-dev \
    libavcodec-dev \
    libavformat-dev \
    libswscale-dev 

RUN apt remove -y python3-numpy
RUN pip3 install torchsummary tqdm
RUN apt-get install -y libjpeg-dev zlib1g-dev
RUN git clone -b v0.3.0 https://github.com/pytorch/vision torchvision
WORKDIR /tmp/torchvision
RUN apt remove -y python3-numpy
RUN pip3 install numpy
RUN python3 setup.py install
RUN rm -fr /tmp/torchvision

#TensorFlow 
RUN apt install -y libhdf5-serial-dev hdf5-tools libhdf5-dev zlib1g-dev zip libjpeg8-dev
RUN pip3 install -U numpy==1.16.1 future==0.17.1 mock==3.0.5 h5py==2.9.0 keras_preprocessing==1.0.5 keras_applications==1.0.8 gast==0.2.2 enum34 futures protobuf

RUN pip3 install --pre --extra-index-url https://developer.download.nvidia.com/compute/redist/jp/v43 tensorflow-gpu


# Sentencepiece from source
WORKDIR /tmp
RUN wget -N https://github.com/google/sentencepiece/archive/v0.1.85.tar.gz -O sentencepiece-0.1.85.tar.gz
RUN tar -zxf sentencepiece-0.1.85.tar.gz
WORKDIR sentencepiece-0.1.85/
RUN mkdir build
WORKDIR build
#RUN cmake ..
RUN mkdir -p /usr/local/lib/python3.6/dist-packages/sentencepiece
RUN cmake .. -DCMAKE_INSTALL_PREFIX="lib/python3.6/dist-packages/sentencepiece"
#RUN cmake ..
RUN make -j $(nproc)
RUN make install
RUN ldconfig -v
ENV PYTHONPATH "${PYTHONPATH}:/usr/local/lib/"

# Tokenizer from compiled wheel
WORKDIR /tmp
RUN pip3 install setuptools
RUN pip3 install setuptools_rust
COPY tokenizers-0.5.2-cp36-cp36m-linux_aarch64.whl /tmp
RUN pip3 install tokenizers-0.5.2-cp36-cp36m-linux_aarch64.whl

# Transfomers from source 
WORKDIR /tmp
RUN git clone https://github.com/huggingface/transformers
WORKDIR transformers
COPY pytorch-transformers/setup.py .
RUN pip3 install .
#COPY transformers-2.7.0-py3-none-any.whl .
#RUN pip3 install transformers-2.7.0-py3-none-any.whl
#ENV PYTHONPATH "${PYTHONPATH}:/usr/lib/python3/dist-packages/"

WORKDIR /root
